module VerifyExamples.Typed.MapTo0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Typed exposing (..)

type Known
    = Known
type Secret
    = Secret





spec0 : Test.Test
spec0 =
    Test.test "#mapTo: \n\n    tag Secret \"secret\"\n        --: Typed Checked Public String\n        |> Typed.wrapAnd (tag Known \"known\")\n        |> Typed.mapTo Secret (\\( secret, _ ) -> secret)\n    --> \"secret\"" <|
        \() ->
            Expect.equal
                (
                tag Secret "secret"
                    --: Typed Checked Public String
                    |> Typed.wrapAnd (tag Known "known")
                    |> Typed.mapTo Secret (\( secret, _ ) -> secret)
                )
                (
                "secret"
                )