module VerifyExamples.Typed.Tag0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Typed exposing (..)

type PasswordTag
    = NowItsSafe
type alias Password =
    Typed Checked PasswordTag Internal String

passwordSafe : Password
passwordSafe =
    tag NowItsSafe "secret1234 th1s iS private oO"



spec0 : Test.Test
spec0 =
    Test.test "#tag: \n\n    passwordSafe |> Typed.internal NowItsSafe\n    --> \"secret1234 th1s iS private oO\"" <|
        \() ->
            Expect.equal
                (
                passwordSafe |> Typed.internal NowItsSafe
                )
                (
                "secret1234 th1s iS private oO"
                )