module VerifyExamples.MARKDOWN.README.Test_0_4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Typed exposing (Typed, Tagged, Public, tag)

type PixelsTag
    = Pixels
type alias Pixels =
    Typed Tagged PixelsTag Public Int

defaultWidth : Pixels
defaultWidth =
    innerWidth
        |> Typed.and borderWidth
        |> Typed.map
            (\( inner, border ) -> inner + border * 2)
borderWidth : Pixels
borderWidth =
    5 |> tag Pixels
innerWidth : Pixels
innerWidth =
    700 |> tag Pixels



spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    defaultWidth |> Typed.untag\n    --> 710" <|
        \() ->
            Expect.equal
                (
                defaultWidth |> Typed.untag
                )
                (
                710
                )