module VerifyExamples.MARKDOWN.README.Test_0_6 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Typed exposing (Typed, Checked, Public, tag)

type EvenTag
    = Even
type alias Even =
    Typed Checked EvenTag Public Int

cakeForEven : Even -> { cake : () }
cakeForEven _ =
    { cake = () }
n2 : Even
n2 =
    2 |> tag Even
multiply : Int -> Even -> Even
multiply factor =
    \even ->
        even
            |> Typed.map (\int -> int * factor)
            |> Typed.toChecked Even



spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    n2 |> multiply -5 |> cakeForEven\n    --> { cake = () }" <|
        \() ->
            Expect.equal
                (
                n2 |> multiply -5 |> cakeForEven
                )
                (
                { cake = () }
                )